#!/usr/bin/env bun

import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"

export interface PublicReleaseManifest {
  schemaVersion: number
  product: string
  release: string
  bundles: Array<{
    target: string
    archive: string
    sha256: string
  }>
}

interface FormulaOptions {
  archiveBaseUrl?: string
  revision?: number
}

const macTargets = ["darwin-arm64", "darwin-x64"] as const

function rejectUnless(condition: boolean, message: string): asserts condition {
  if (!condition) throw new Error(message)
}

function bundleFor(
  manifest: PublicReleaseManifest,
  target: typeof macTargets[number],
) {
  const matches = manifest.bundles.filter((bundle) => bundle.target === target)
  rejectUnless(matches.length !== 0, `missing ${target} archive`)
  rejectUnless(matches.length === 1, `duplicate ${target} archive`)
  const bundle = matches[0]!
  rejectUnless(
    bundle.archive === `muxvia-${manifest.release}-${target}.tar.gz`,
    `unexpected ${target} archive`,
  )
  rejectUnless(/^[0-9a-f]{64}$/.test(bundle.sha256), `invalid ${target} sha256`)
  return bundle
}

function archiveUrl(baseUrl: string, archive: string): string {
  const base = new URL(baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`)
  rejectUnless(["file:", "https:"].includes(base.protocol), "archive base URL must use https or file")
  return new URL(archive, base).toString()
}

export function createHomebrewFormula(
  manifest: PublicReleaseManifest,
  options: FormulaOptions = {},
): string {
  rejectUnless(manifest.schemaVersion === 1, "unsupported public release manifest")
  rejectUnless(manifest.product === "muxvia", "unexpected public release product")
  rejectUnless(/^\d+\.\d+\.\d+$/.test(manifest.release), "invalid public release version")
  rejectUnless(Array.isArray(manifest.bundles), "invalid public release bundles")
  const revision = options.revision
  rejectUnless(
    revision === undefined || (Number.isInteger(revision) && revision > 0),
    "revision must be a positive integer",
  )
  const baseUrl = options.archiveBaseUrl
    ?? `https://github.com/HaroldHuanrongLIU/muxvia/releases/download/v${manifest.release}`
  const arm = bundleFor(manifest, "darwin-arm64")
  const intel = bundleFor(manifest, "darwin-x64")

  return `# This file is generated by scripts/homebrew-formula.ts. Do not edit it by hand.
class Muxvia < Formula
  desc "Terminal-native control plane for AI coding command-line tools"
  homepage "https://github.com/HaroldHuanrongLIU/muxvia"
  version "${manifest.release}"
  license "MIT"
${revision === undefined ? "" : `  revision ${revision}\n`}
  depends_on :macos

  on_arm do
    url "${archiveUrl(baseUrl, arm.archive)}"
    sha256 "${arm.sha256}"
  end

  on_intel do
    url "${archiveUrl(baseUrl, intel.archive)}"
    sha256 "${intel.sha256}"
  end

  def install
    # Homebrew expects one conventional license metafile at the keg root. Keep
    # that copy from relocating the manifest-bound LICENSE out of libexec.
    prefix.install "LICENSE"
    libexec.install(
      "muxvia",
      "muxvia-routing",
      "muxvia-release.json",
      "THIRD_PARTY_NOTICES.md",
      "EXTRACTION_MANIFEST.json",
    )
    cp prefix/"LICENSE", libexec/"LICENSE"
    bin.install_symlink libexec/"muxvia"
  end

  def caveats
    <<~EOS
      Muxvia's initial macOS release is unsigned and unnotarized. Gatekeeper may
      require explicit approval in System Settings > Privacy & Security.

      The complete, versioned Release Bundle is installed at:
        #{libexec}
      Muxvia does not modify or self-upgrade this Homebrew-owned tree. Upgrade
      or repair the complete bundle with:
        brew upgrade muxvia
        brew reinstall muxvia

      Third-party notices are installed at:
        #{libexec}/THIRD_PARTY_NOTICES.md
    EOS
  end

  test do
    assert_equal 6, libexec.children.length
    assert_predicate libexec/"muxvia-routing", :executable?
    assert_path_exists libexec/"muxvia-release.json"
    output = shell_output("#{bin}/muxvia version --json")
    assert_match %("product":"muxvia"), output
    assert_match %("release":"#{version}"), output
  end
end
`
}

function option(args: string[], name: string): string {
  const index = args.indexOf(name)
  const value = index >= 0 ? args[index + 1] : undefined
  if (!value || value.startsWith("--")) throw new Error(`missing ${name}`)
  return value
}

async function expectedFormula(args: string[]): Promise<string> {
  const manifestPath = resolve(option(args, "--manifest"))
  const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as PublicReleaseManifest
  const baseUrl = args.includes("--archive-base-url")
    ? option(args, "--archive-base-url")
    : undefined
  const revisionValue = args.includes("--revision") ? option(args, "--revision") : undefined
  const revision = revisionValue === undefined ? undefined : Number(revisionValue)
  return createHomebrewFormula(manifest, { archiveBaseUrl: baseUrl, revision })
}

async function main(): Promise<void> {
  const command = Bun.argv[2]
  const args = Bun.argv.slice(3)
  const output = resolve(option(args, command === "verify" ? "--formula" : "--output"))
  const expected = await expectedFormula(args)
  if (command === "generate") {
    await mkdir(dirname(output), { recursive: true })
    await writeFile(output, expected, { encoding: "utf8", flag: "wx", mode: 0o644 })
    return
  }
  if (command === "verify") {
    rejectUnless(await readFile(output, "utf8") === expected, "Homebrew formula is not reproducible")
    return
  }
  throw new Error("expected generate or verify")
}

if (import.meta.main) await main()
